### ISSUE TITLE
Not detecting the latest version of some crates

### ISSUE THREAD

**Issue by tylerlaprade** [BarbossHack/crates-io#5] opened 2024-12-26 20:21 UTC
# Bug report

**Describe the bug**
Six of my dependencies have newer versions, but this extension only knows about two of them.

**To Reproduce**

1. Add `chrono = "0.4.38"` to your dependencies

**Expected behavior**
A red X with the latest version, `0.4.39` as of the time of this bug report

**Screenshots**
The left emoji is from this package, while the right is from Dependi. Dependi correctly flags any outdated crates.
<img width="1278" alt="image" src="https://github.com/user-attachments/assets/f64f19ec-f5ca-4c49-800f-e289bb829eef" />

**Extension version:**

`0.7.3`

**Desktop version:**

- OS: MacOS
- Version Sonoma 14.5

**Additional context**
Dependi is working properly

**Comment by BarbossHack** [comment] 2024-12-28 19:49
I do not have this behavior in v0.7.3 (linux)
![image](https://github.com/user-attachments/assets/5fa1b395-c7fa-4220-a838-bb554a11cbba)

Could you provide your full Cargo.toml (in attachment) please ? So I can look into it

Also, could you try to reload you project ? (close vscode and reopen it)

**Comment by BarbossHack** [comment] 2024-12-29 16:33
I misunderstood your issue, please ignore my previous comment.

The expected behavior of this crate is to display the green checkmark ✅ when your Cargo.toml is up to date, following the "Cargo" rules.

According to Cargo versionning rules (https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html), when you set "0.4.38" cargo will use the last minor version, here 0.4.39 (look at the example : _0.2.3  :=  >=0.2.3, <0.3.0_) so your Cargo.toml is **in fact** up to date ✅

Maybe Dependi wants to tell you that you *could* update the minor version in your Cargo.toml, but the is in fact _useless_ as cargo will treat it the same way 👍

I will close this issue as this is not a bug but the expected behavior, but fill free to comment or reopen a new issue 🙏

**Closed** 2024-12-29 16:34 UTC

**Comment by tylerlaprade** [comment] 2024-12-30 02:20
I see, thanks for clarifying. I didn't realize Rust dependencies work in this terrible way. It's unimaginable that there's no way to pin a specific version. It's extra unimaginable that a separate caret syntax exists and does literally nothing.

**Comment by BarbossHack** [comment] 2024-12-30 07:20
Well, please take the time to read the whole page https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html

You can pin a specific version like this

chrono = "=0.4.38"

You can do everything you want with cargo versions

**Comment by tylerlaprade** [comment] 2024-12-30 18:26
>minor versions don't have breaking changes

All changes have the potential to be breaking, whether the developer intends it or not 😉
But thanks for pointing that out. I did not notice that footnote of a footnote the first time around.
And thanks for maintaining this project after the Dependi switcheroo!

**Comment by BarbossHack** [comment] 2024-12-30 18:27
You're welcome 🚀
